name: Shell Check

on:
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/shell-check.yml'
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shell-check.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bash syntax check
        run: bash -n cf-cert.sh

      - name: ShellCheck
        run: shellcheck cf-cert.sh
